//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustCompute.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStringsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStringsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JustCompute.Resources.Strings.AppStringsRes", typeof(AppStringsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom location.
        /// </summary>
        public static string AddCustomLocationLabel {
            get {
                return ResourceManager.GetString("AddCustomLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        public static string AddLocationLabel {
            get {
                return ResourceManager.GetString("AddLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annular.
        /// </summary>
        public static string AnnularEclipseLabel {
            get {
                return ResourceManager.GetString("AnnularEclipseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annular or Total eclipse begin time: {0}.
        /// </summary>
        public static string AorTEclipseBeginTimeLabel {
            get {
                return ResourceManager.GetString("AorTEclipseBeginTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annular or Total eclipse end time: {0}.
        /// </summary>
        public static string AorTEclipseEndTimeLabel {
            get {
                return ResourceManager.GetString("AorTEclipseEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annular or Total eclipse duration: {0}.
        /// </summary>
        public static string AorTSolarEclipseDurationLabel {
            get {
                return ResourceManager.GetString("AorTSolarEclipseDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarius.
        /// </summary>
        public static string AquariusLabel {
            get {
                return ResourceManager.GetString("AquariusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aries.
        /// </summary>
        public static string AriesLabel {
            get {
                return ResourceManager.GetString("AriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At these coordinates:.
        /// </summary>
        public static string AtTheseCoordinatesLabel {
            get {
                return ResourceManager.GetString("AtTheseCoordinatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beaver Moon.
        /// </summary>
        public static string BeaverMoonLabel {
            get {
                return ResourceManager.GetString("BeaverMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Moon.
        /// </summary>
        public static string BlueMoonLabel {
            get {
                return ResourceManager.GetString("BlueMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buck Moon.
        /// </summary>
        public static string BuckMoonLabel {
            get {
                return ResourceManager.GetString("BuckMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        public static string CancerLabel {
            get {
                return ResourceManager.GetString("CancerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get your&apos;s current location, please, check app permissions and try again later.
        /// </summary>
        public static string CannotGetCurrentLocationError {
            get {
                return ResourceManager.GetString("CannotGetCurrentLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get current location. Please, try later.
        /// </summary>
        public static string CannotGetCurrentLocationLabel {
            get {
                return ResourceManager.GetString("CannotGetCurrentLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get any location.
        /// </summary>
        public static string CannotGetLocationLabel {
            get {
                return ResourceManager.GetString("CannotGetLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorn.
        /// </summary>
        public static string CapricornLabel {
            get {
                return ResourceManager.GetString("CapricornLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Moon.
        /// </summary>
        public static string ColdMoonLabel {
            get {
                return ResourceManager.GetString("ColdMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converters.
        /// </summary>
        public static string ConvertersLabel {
            get {
                return ResourceManager.GetString("ConvertersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates Converter.
        /// </summary>
        public static string CoordinatesConverterLabel {
            get {
                return ResourceManager.GetString("CoordinatesConverterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corn Moon.
        /// </summary>
        public static string CornMoonLabel {
            get {
                return ResourceManager.GetString("CornMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0:dd MMMM yyyy}.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0:dd MMMM yyyy hh:mm:ss}.
        /// </summary>
        public static string DateWithTimeLabel {
            get {
                return ResourceManager.GetString("DateWithTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day duration: {0}.
        /// </summary>
        public static string DayDurationLabel {
            get {
                return ResourceManager.GetString("DayDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digraph (MGRS 100,000 Meter Square Identifier): {0}.
        /// </summary>
        public static string DigraphLabel {
            get {
                return ResourceManager.GetString("DigraphLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: {0:0.##} {1}.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Unit.
        /// </summary>
        public static string DistanceUnitLabel {
            get {
                return ResourceManager.GetString("DistanceUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eclipses.
        /// </summary>
        public static string EclipsesLabel {
            get {
                return ResourceManager.GetString("EclipsesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit saved locations.
        /// </summary>
        public static string EditSavedLocationsLabel {
            get {
                return ResourceManager.GetString("EditSavedLocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string FeetsAbbreviationLabel {
            get {
                return ResourceManager.GetString("FeetsAbbreviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feets.
        /// </summary>
        public static string FeetsLabel {
            get {
                return ResourceManager.GetString("FeetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First quarter.
        /// </summary>
        public static string FirstQuarterLabel {
            get {
                return ResourceManager.GetString("FirstQuarterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Moon.
        /// </summary>
        public static string FullMoonLabel {
            get {
                return ResourceManager.GetString("FullMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        public static string GeminiLabel {
            get {
                return ResourceManager.GetString("GeminiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Settings.
        /// </summary>
        public static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunters Moon.
        /// </summary>
        public static string HuntersMoonLabel {
            get {
                return ResourceManager.GetString("HuntersMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Flattening: {0}.
        /// </summary>
        public static string InverseFlatteningLabel {
            get {
                return ResourceManager.GetString("InverseFlatteningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string KilometersAbbreviationLabel {
            get {
                return ResourceManager.GetString("KilometersAbbreviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string KmLabel {
            get {
                return ResourceManager.GetString("KmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last quarter.
        /// </summary>
        public static string LastQuarterLabel {
            get {
                return ResourceManager.GetString("LastQuarterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LatitudeLabel {
            get {
                return ResourceManager.GetString("LatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0:0.#####}.
        /// </summary>
        public static string LatitudeStringFormatLabel {
            get {
                return ResourceManager.GetString("LatitudeStringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        public static string LeoLabel {
            get {
                return ResourceManager.GetString("LeoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        public static string LibraLabel {
            get {
                return ResourceManager.GetString("LibraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LocationNameLabel {
            get {
                return ResourceManager.GetString("LocationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App needs access device location to operate.
        /// </summary>
        public static string LocationPermissionDialogMessage {
            get {
                return ResourceManager.GetString("LocationPermissionDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Permission.
        /// </summary>
        public static string LocationPermissionDialogTitle {
            get {
                return ResourceManager.GetString("LocationPermissionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationsLabel {
            get {
                return ResourceManager.GetString("LocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude: {0:0.#####}.
        /// </summary>
        public static string LongitudeStringFormatLabel {
            get {
                return ResourceManager.GetString("LongitudeStringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum eclipse time: {0}.
        /// </summary>
        public static string MaximumSolarEclispseTimeLabel {
            get {
                return ResourceManager.GetString("MaximumSolarEclispseTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string MetersAbbreviationLabel {
            get {
                return ResourceManager.GetString("MetersAbbreviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string MetersLabel {
            get {
                return ResourceManager.GetString("MetersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS Easting: {0}.
        /// </summary>
        public static string MGRSEastingLabel {
            get {
                return ResourceManager.GetString("MGRSEastingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string MGRSLabel {
            get {
                return ResourceManager.GetString("MGRSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS Latitude Band Grid Zone Designation: {0}.
        /// </summary>
        public static string MGRSLatZoneLabel {
            get {
                return ResourceManager.GetString("MGRSLatZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS Longitude Band Grid Zone Designation: {0}.
        /// </summary>
        public static string MGRSLonZoneLabel {
            get {
                return ResourceManager.GetString("MGRSLonZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS Northing: {0}.
        /// </summary>
        public static string MGRSNorthingLabel {
            get {
                return ResourceManager.GetString("MGRSNorthingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS Type: {0}.
        /// </summary>
        public static string MGRSTypeLabel {
            get {
                return ResourceManager.GetString("MGRSTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid eclipse time: {0}.
        /// </summary>
        public static string MidLunarEclipseTimeLabel {
            get {
                return ResourceManager.GetString("MidLunarEclipseTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string MilesAbbreviationLabel {
            get {
                return ResourceManager.GetString("MilesAbbreviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string MilesLabel {
            get {
                return ResourceManager.GetString("MilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon Eclipses.
        /// </summary>
        public static string MoonEclipsesLabel {
            get {
                return ResourceManager.GetString("MoonEclipsesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon in: {0}.
        /// </summary>
        public static string MoonInZodiacSignLabel {
            get {
                return ResourceManager.GetString("MoonInZodiacSignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        public static string MoonLabel {
            get {
                return ResourceManager.GetString("MoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon name: .
        /// </summary>
        public static string MoonNameLabel {
            get {
                return ResourceManager.GetString("MoonNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonphase: .
        /// </summary>
        public static string MoonPhaseLabel {
            get {
                return ResourceManager.GetString("MoonPhaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonrise duration: {0}.
        /// </summary>
        public static string MoonRiseDurationLabel {
            get {
                return ResourceManager.GetString("MoonRiseDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonrise: {0}.
        /// </summary>
        public static string MoonRiseLabel {
            get {
                return ResourceManager.GetString("MoonRiseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonset: {0}.
        /// </summary>
        public static string MoonSetLabel {
            get {
                return ResourceManager.GetString("MoonSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nmi.
        /// </summary>
        public static string NauticalMilesAbbreviationLabel {
            get {
                return ResourceManager.GetString("NauticalMilesAbbreviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles .
        /// </summary>
        public static string NauticalMilesLabel {
            get {
                return ResourceManager.GetString("NauticalMilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Moon.
        /// </summary>
        public static string NewMoonLabel {
            get {
                return ResourceManager.GetString("NewMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any saved locations yet, press &quot;+&quot; button to add.
        /// </summary>
        public static string NoSavedLocationsLabel {
            get {
                return ResourceManager.GetString("NoSavedLocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        public static string PartialEclipseLabel {
            get {
                return ResourceManager.GetString("PartialEclipseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial eclipse begin time: {0}.
        /// </summary>
        public static string PartialLunarEclipseBeginTimeLabel {
            get {
                return ResourceManager.GetString("PartialLunarEclipseBeginTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial eclipse end time: {0}.
        /// </summary>
        public static string PartialLunarEclipseEndTimeLabel {
            get {
                return ResourceManager.GetString("PartialLunarEclipseEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial eclipse begin time: {0}.
        /// </summary>
        public static string PartialSolarEclipseBeginTimeLabel {
            get {
                return ResourceManager.GetString("PartialSolarEclipseBeginTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial eclipse end time: {0}.
        /// </summary>
        public static string PartialSolarEclipseEndTimeLabel {
            get {
                return ResourceManager.GetString("PartialSolarEclipseEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penumbral.
        /// </summary>
        public static string PenumbralEclipseLabel {
            get {
                return ResourceManager.GetString("PenumbralEclipseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penumbral eclipse begin time: {0}.
        /// </summary>
        public static string PenumbralLunarEclipseBeginTimeLabel {
            get {
                return ResourceManager.GetString("PenumbralLunarEclipseBeginTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penumbral eclipse end time: {0}.
        /// </summary>
        public static string PenumbralLunarEclipseEndTimeLabel {
            get {
                return ResourceManager.GetString("PenumbralLunarEclipseEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App needs location permission to operate. Go to app settings and grand permission or close the app.
        /// </summary>
        public static string PermissionRequiredDialogMessage {
            get {
                return ResourceManager.GetString("PermissionRequiredDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission required.
        /// </summary>
        public static string PermissionRequiredDialogTitle {
            get {
                return ResourceManager.GetString("PermissionRequiredDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink Moon.
        /// </summary>
        public static string PinkMoonLabel {
            get {
                return ResourceManager.GetString("PinkMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisces.
        /// </summary>
        public static string PiscesLabel {
            get {
                return ResourceManager.GetString("PiscesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Location.
        /// </summary>
        public static string PlusAddLocationLabel {
            get {
                return ResourceManager.GetString("PlusAddLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population: {0:N0}.
        /// </summary>
        public static string PopulationLabel {
            get {
                return ResourceManager.GetString("PopulationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarius.
        /// </summary>
        public static string SagittariusLabel {
            get {
                return ResourceManager.GetString("SagittariusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved locations:.
        /// </summary>
        public static string SavedLocationsLabel {
            get {
                return ResourceManager.GetString("SavedLocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location.
        /// </summary>
        public static string SaveLocationButtonText {
            get {
                return ResourceManager.GetString("SaveLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpio.
        /// </summary>
        public static string ScorpioLabel {
            get {
                return ResourceManager.GetString("ScorpioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search city.
        /// </summary>
        public static string SearchCityLabel {
            get {
                return ResourceManager.GetString("SearchCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholderLabel {
            get {
                return ResourceManager.GetString("SearchPlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets and Rises.
        /// </summary>
        public static string SetsAndRisesLabel {
            get {
                return ResourceManager.GetString("SetsAndRisesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow Moon.
        /// </summary>
        public static string SnowMoonLabel {
            get {
                return ResourceManager.GetString("SnowMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strawberry Moon.
        /// </summary>
        public static string StrawberryMoonLabel {
            get {
                return ResourceManager.GetString("StrawberryMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sturgeon Moon.
        /// </summary>
        public static string SturgeonMoonLabel {
            get {
                return ResourceManager.GetString("SturgeonMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun &amp; Moon.
        /// </summary>
        public static string SunAndMoonLabel {
            get {
                return ResourceManager.GetString("SunAndMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Eclipses.
        /// </summary>
        public static string SunEclipsesLabel {
            get {
                return ResourceManager.GetString("SunEclipsesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        public static string SunEclispseTypeLabel {
            get {
                return ResourceManager.GetString("SunEclispseTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string SunLabel {
            get {
                return ResourceManager.GetString("SunLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise: {0}.
        /// </summary>
        public static string SunRiseLabel {
            get {
                return ResourceManager.GetString("SunRiseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset: {0}.
        /// </summary>
        public static string SunSetLabel {
            get {
                return ResourceManager.GetString("SunSetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurus.
        /// </summary>
        public static string TaurusLabel {
            get {
                return ResourceManager.GetString("TaurusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0}.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Travel.
        /// </summary>
        public static string TimeTravelLabel {
            get {
                return ResourceManager.GetString("TimeTravelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalEclipseLabel {
            get {
                return ResourceManager.GetString("TotalEclipseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total eclipse begin time: {0}.
        /// </summary>
        public static string TotalLunarEclipseBeginTimeLabel {
            get {
                return ResourceManager.GetString("TotalLunarEclipseBeginTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total eclipse end time: {0}.
        /// </summary>
        public static string TotalLunarEclipseEndTimeLabel {
            get {
                return ResourceManager.GetString("TotalLunarEclipseEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}{0}, {1}.
        /// </summary>
        public static string TwoValuesSeparatedByComa {
            get {
                return ResourceManager.GetString("TwoValuesSeparatedByComa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Location.
        /// </summary>
        public static string UnknownLocationLabel {
            get {
                return ResourceManager.GetString("UnknownLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 24-hour format.
        /// </summary>
        public static string Use24HourTimeFormatLabel {
            get {
                return ResourceManager.GetString("Use24HourTimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC Time Offset.
        /// </summary>
        public static string UTCTimeOffsetLabel {
            get {
                return ResourceManager.GetString("UTCTimeOffsetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM Easting: {0}.
        /// </summary>
        public static string UTMEastingLabel {
            get {
                return ResourceManager.GetString("UTMEastingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string UTMLabel {
            get {
                return ResourceManager.GetString("UTMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM Latitude Band Grid Zone Designation: {0}.
        /// </summary>
        public static string UTMLatZoneLabel {
            get {
                return ResourceManager.GetString("UTMLatZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM Longitude Band Grid Zone Designation: {0}.
        /// </summary>
        public static string UTMLonZoneLabel {
            get {
                return ResourceManager.GetString("UTMLonZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM Northing: {0}.
        /// </summary>
        public static string UTMNorthingLabel {
            get {
                return ResourceManager.GetString("UTMNorthingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM Type: {0}.
        /// </summary>
        public static string UTMTypeLabel {
            get {
                return ResourceManager.GetString("UTMTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgo.
        /// </summary>
        public static string VirgoLabel {
            get {
                return ResourceManager.GetString("VirgoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning Crescent.
        /// </summary>
        public static string WaningCrescentLabel {
            get {
                return ResourceManager.GetString("WaningCrescentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning Gibbous.
        /// </summary>
        public static string WaningGibbousLabel {
            get {
                return ResourceManager.GetString("WaningGibbousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing Crescent.
        /// </summary>
        public static string WaxingCrescentLabel {
            get {
                return ResourceManager.GetString("WaxingCrescentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing Gibbous.
        /// </summary>
        public static string WaxingGibbousLabel {
            get {
                return ResourceManager.GetString("WaxingGibbousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf Moon.
        /// </summary>
        public static string WolfMoonLabel {
            get {
                return ResourceManager.GetString("WolfMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worm Moon.
        /// </summary>
        public static string WormMoonLabel {
            get {
                return ResourceManager.GetString("WormMoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zodiac: {0}.
        /// </summary>
        public static string ZodiacSignLabel {
            get {
                return ResourceManager.GetString("ZodiacSignLabel", resourceCulture);
            }
        }
    }
}
